name = "WildLight"
author = "Alfakynz"
version = "5.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "151705642b94ec0ad68630a3f69db74823fe2c21918c153eb2ae2cc53239740f"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
