name = "WildLight"
author = "Alfakynz"
version = "4.5.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86ee96e2e85729cdfd286e017d901c53674214150b08e7cb449ff9f450f43883"

[versions]
fabric = "0.18.6"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
