name = "WildLight"
author = "Alfakynz"
version = "4.6.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dff52cb084a013815cb98adda7a83e59776043a6555fcaba89bf80f75aaed5fa"

[versions]
fabric = "0.19.2"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
