name = "WildLight"
author = "Alfakynz"
version = "5.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e6b54eef637c4b8e22b80c3b7bfa1d0781b0a64416bd87b0f4834455e54dbc55"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
