name = "WildLight"
author = "Alfakynz"
version = "5.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "22b3d34e79740c84872f5a621b42321b328609ebc65d53bb47eabe790b38e6f0"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
